#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Pimp Your Terminal - Automated Oh My Posh Setup
.DESCRIPTION
    Installs Oh My Posh, Nerd Fonts, Terminal-Icons, and configures
    the Cloud Native Azure theme with useful PSReadLine enhancements
. NOTES
    Run this script in an elevated PowerShell terminal
    Author: Ricky-G
    Date: 2025-12-29
. LINK
    https://ohmyposh.dev/docs/themes
#>

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Pimp Your Terminal - Setup Script" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Store paths upfront
$localAppData = $env:LOCALAPPDATA
$tempFolder = $env:TEMP

# ============================================
# STEP 1: Install Oh My Posh
# ============================================
Write-Host "Step 1: Installing Oh My Posh..." -ForegroundColor Yellow

$hasWinget = $false
try {
    $hasWinget = (Get-Command winget -ErrorAction SilentlyContinue) -ne $null
} catch {
    $hasWinget = $false
}

if ($hasWinget) {
    Write-Host "  Using winget to install Oh My Posh..." -ForegroundColor Gray
    winget install JanDeDobbeleer.OhMyPosh -s winget --accept-package-agreements --accept-source-agreements
} else {
    Write-Host "  Winget not found.  Downloading Oh My Posh directly..." -ForegroundColor Gray
    $installScript = Join-Path $tempFolder "install-ohmyposh.ps1"
    Invoke-WebRequest -Uri "https://ohmyposh.dev/install.ps1" -OutFile $installScript -UseBasicParsing
    & $installScript
}

# Refresh PATH
$machinePath = [Environment]::GetEnvironmentVariable("Path", "Machine")
$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
$env:Path = $machinePath + ";" + $userPath

# Add Oh My Posh install location to current session
$ohMyPoshPath = Join-Path $localAppData "Programs\oh-my-posh\bin"
if (Test-Path $ohMyPoshPath) {
    $env:Path = $env:Path + ";" + $ohMyPoshPath
}

# Verify Oh My Posh is installed
$ohMyPoshInstalled = $false
try {
    $ohMyPoshInstalled = (Get-Command oh-my-posh -ErrorAction SilentlyContinue) -ne $null
} catch {
    $ohMyPoshInstalled = $false
}

if (-not $ohMyPoshInstalled) {
    Write-Host "  ERROR: Oh My Posh installation failed." -ForegroundColor Red
    Write-Host "  Please install manually from https://ohmyposh.dev" -ForegroundColor Red
    exit 1
}

Write-Host "  Oh My Posh installed successfully!" -ForegroundColor Green

# ============================================
# STEP 2: Install Nerd Font
# ============================================
Write-Host "`nStep 2: Installing Nerd Font (Meslo)..." -ForegroundColor Yellow
Write-Host "  This may take a moment..." -ForegroundColor Gray

try {
    oh-my-posh font install Meslo
    Write-Host "  Nerd Font installed successfully!" -ForegroundColor Green
} catch {
    Write-Host "  Font installation failed.  You may need to install manually." -ForegroundColor Yellow
    Write-Host "  Download from: https://github.com/ryanoasis/nerd-fonts/releases" -ForegroundColor Yellow
}

# ============================================
# STEP 3: Install Terminal-Icons Module
# ============================================
Write-Host "`nStep 3: Installing Terminal-Icons module..." -ForegroundColor Yellow

try {
    if (-not (Get-Module -ListAvailable -Name Terminal-Icons)) {
        Install-Module -Name Terminal-Icons -Repository PSGallery -Force -Scope CurrentUser
        Write-Host "  Terminal-Icons installed successfully!" -ForegroundColor Green
    } else {
        Write-Host "  Terminal-Icons already installed." -ForegroundColor Green
    }
} catch {
    Write-Host "  Terminal-Icons installation failed.  This is optional." -ForegroundColor Yellow
}

# ============================================
# STEP 4: Configure PowerShell Profile
# ============================================
Write-Host "`nStep 4: Configuring PowerShell profile..." -ForegroundColor Yellow

# Theme URL
$themeUrl = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/cloud-native-azure.omp.json"

# Build the profile content with all the good stuff
$profileContent = @'
# ============================================
# PowerShell Profile - Pimp Your Terminal
# ============================================
# Auto-generated by pimp-my-terminal.ps1
# Author: Ricky-G
# Date:  2025-12-29

# --------------------------------------------
# Oh My Posh - Cloud Native Azure Theme
# Shows:  Git status, Kubernetes context, Azure subscription
# --------------------------------------------
'@ + "`noh-my-posh init pwsh --config '" + $themeUrl + "' | Invoke-Expression`n" + @'

# --------------------------------------------
# Terminal-Icons - Show file/folder icons in ls
# --------------------------------------------
if (Get-Module -ListAvailable -Name Terminal-Icons) {
    Import-Module -Name Terminal-Icons
}

# --------------------------------------------
# PSReadLine Enhancements
# --------------------------------------------
if ($host.Name -eq 'ConsoleHost') {
    # Import PSReadLine if not already loaded
    if (-not (Get-Module PSReadLine)) {
        Import-Module PSReadLine
    }

    # History search with Up/Down arrows
    # Type partial command, then Up arrow to find matching history
    Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward
    Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward

    # Show predictions from history as you type (grayed out text)
    # Only set PredictionSource if PSReadLine 2.1+ is installed
    $psrVersion = (Get-Module PSReadLine).Version
    if ($psrVersion -ge [version]"2.1.0") {
        Set-PSReadLineOption -PredictionSource History
    }
    Set-PSReadLineOption -HistorySearchCursorMovesToEnd

    # Optional: Show predictions as a list instead of inline
    # Set-PSReadLineOption -PredictionViewStyle ListView

    # --------------------------------------------
    # F7 - History Grid View
    # Press F7 to see a searchable grid of command history
    # --------------------------------------------
    Set-PSReadLineKeyHandler -Key F7 `
        -BriefDescription History `
        -LongDescription 'Show command history in a grid view' `
        -ScriptBlock {
        $pattern = $null
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$pattern, [ref]$null)
        if ($pattern) {
            $pattern = [regex]:: Escape($pattern)
        }

        $history = [System.Collections.ArrayList]@(
            $last = ''
            $lines = ''
            foreach ($line in [System.IO.File]::ReadLines((Get-PSReadLineOption).HistorySavePath)) {
                if ($line. EndsWith('`')) {
                    $lines = if ($lines) { "$lines`n$line" } else { $line }
                    continue
                }
                if ($lines) {
                    $line = "$lines`n$line"
                    $lines = ''
                }
                if (($line -cne $last) -and (!$pattern -or ($line -match $pattern))) {
                    $last = $line
                    $line
                }
            }
        )
        $history. Reverse()

        $command = $history | Out-GridView -Title 'Command History - Select to Insert' -PassThru
        if ($command) {
            [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()
            [Microsoft.PowerShell.PSConsoleReadLine]::Insert(($command -join "`n"))
        }
    }

    # --------------------------------------------
    # Dotnet Build/Test Shortcuts
    # Ctrl+Shift+B - Run dotnet build
    # Ctrl+Shift+T - Run dotnet test
    # --------------------------------------------
    Set-PSReadLineKeyHandler -Key Ctrl+Shift+b `
        -BriefDescription BuildDotnet `
        -LongDescription 'Run dotnet build' `
        -ScriptBlock {
        [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()
        [Microsoft.PowerShell.PSConsoleReadLine]::Insert('dotnet build')
        [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
    }

    Set-PSReadLineKeyHandler -Key Ctrl+Shift+t `
        -BriefDescription TestDotnet `
        -LongDescription 'Run dotnet test' `
        -ScriptBlock {
        [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()
        [Microsoft.PowerShell.PSConsoleReadLine]::Insert('dotnet test')
        [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
    }
}

# --------------------------------------------
# Tab Completion for Winget
# --------------------------------------------
Register-ArgumentCompleter -Native -CommandName winget -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    [Console]::InputEncoding = [Console]::OutputEncoding = $OutputEncoding = [System.Text.Utf8Encoding]:: new()
    $Local:word = $wordToComplete. Replace('"', '""')
    $Local:ast = $commandAst. ToString().Replace('"', '""')
    winget complete --word="$Local:word" --commandline "$Local:ast" --position $cursorPosition | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
    }
}

# --------------------------------------------
# Tab Completion for Dotnet CLI
# --------------------------------------------
Register-ArgumentCompleter -Native -CommandName dotnet -ScriptBlock {
    param($commandName, $wordToComplete, $cursorPosition)
    dotnet complete --position $cursorPosition "$wordToComplete" | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
    }
}

# --------------------------------------------
# End of Profile
# --------------------------------------------
'@

# Ensure profile directory exists
$profileDir = Split-Path -Parent $PROFILE
if (-not (Test-Path $profileDir)) {
    New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
}

# Write the profile
Set-Content -Path $PROFILE -Value $profileContent -Force
Write-Host "  PowerShell profile configured!" -ForegroundColor Green
Write-Host "  Profile location: $PROFILE" -ForegroundColor Gray

# ============================================
# STEP 5: Verify Configuration
# ============================================
Write-Host "`nStep 5: Verifying configuration..." -ForegroundColor Yellow

$verifyContent = Get-Content $PROFILE -Raw
$checks = @(
    @{Name = "Oh My Posh theme"; Pattern = "cloud-native-azure"},
    @{Name = "Terminal-Icons"; Pattern = "Terminal-Icons"},
    @{Name = "PSReadLine history search"; Pattern = "HistorySearchBackward"},
    @{Name = "F7 History Grid"; Pattern = "Out-GridView"},
    @{Name = "Dotnet build shortcut"; Pattern = "Ctrl\+Shift\+b"},
    @{Name = "Dotnet test shortcut"; Pattern = "Ctrl\+Shift\+t"},
    @{Name = "Winget tab completion"; Pattern = "winget complete"},
    @{Name = "Dotnet tab completion"; Pattern = "dotnet complete"}
)

foreach ($check in $checks) {
    if ($verifyContent -match $check.Pattern) {
        Write-Host "  [OK] $($check.Name)" -ForegroundColor Green
    } else {
        Write-Host "  [MISSING] $($check. Name)" -ForegroundColor Yellow
    }
}

# ============================================
# DONE! 
# ============================================
Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  Setup Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "What's Installed:" -ForegroundColor Magenta
Write-Host "  - Oh My Posh with Cloud Native Azure theme"
Write-Host "  - Meslo Nerd Font (for icons and glyphs)"
Write-Host "  - Terminal-Icons (file/folder icons in ls)"
Write-Host "  - PSReadLine enhancements (history search, predictions)"
Write-Host "  - Tab completion for winget and dotnet"
Write-Host ""
Write-Host "Theme Features:" -ForegroundColor Magenta
Write-Host "  - Kubernetes context and namespace"
Write-Host "  - Azure subscription"
Write-Host "  - Git branch and status"
Write-Host "  - Session info, battery, and time"
Write-Host ""
Write-Host "========================================" -ForegroundColor Yellow
Write-Host "  IMPORTANT - Manual Steps Required" -ForegroundColor Yellow
Write-Host "========================================" -ForegroundColor Yellow
Write-Host ""
Write-Host "1. Set your terminal font to 'MesloLGM Nerd Font':" -ForegroundColor Cyan
Write-Host ""
Write-Host "   Windows Terminal:" -ForegroundColor White
Write-Host "     Settings > Profiles > Defaults > Appearance > Font face"
Write-Host ""
Write-Host "   VS Code:" -ForegroundColor White
Write-Host "     Settings > Terminal > Integrated:  Font Family"
Write-Host "     Set to:  MesloLGM Nerd Font"
Write-Host ""
Write-Host "2. Close this terminal and open a new one" -ForegroundColor Cyan
Write-Host ""
Write-Host "========================================" -ForegroundColor Gray
Write-Host "  Keyboard Shortcuts" -ForegroundColor Gray
Write-Host "========================================" -ForegroundColor Gray
Write-Host ""
Write-Host "  Up/Down Arrow   - Search history by what you've typed" -ForegroundColor White
Write-Host "  F7              - Open history grid (searchable popup)" -ForegroundColor White
Write-Host "  Ctrl+Shift+B    - Run 'dotnet build'" -ForegroundColor White
Write-Host "  Ctrl+Shift+T    - Run 'dotnet test'" -ForegroundColor White
Write-Host "  Tab             - Auto-complete (winget, dotnet)" -ForegroundColor White
Write-Host ""
Write-Host "Browse all themes:  https://ohmyposh.dev/docs/themes" -ForegroundColor Gray
Write-Host ""
